# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-10-09 16:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_partner_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('short_description', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('course_run_publisher', models.CharField(help_text='Used to identify publisher for the Partner (e.g. for CourseRunMarketingSitePublisher purposes.)', max_length=15, unique=True, verbose_name='Course Run Publisher')),
            ],
            options={
                'verbose_name_plural': 'Marketing Services',
            },
        ),
        migrations.AddField(
            model_name='partner',
            name='marketing_site_service',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.MarketingService'),
        ),
    ]
