# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-10-12 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_marketingservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='lms_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='LMS URL'),
        ),
    ]
