# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-10-18 16:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0057_courserun_wordpress_post_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='UUID')),
                ('lms_web_url', models.URLField(blank=True, null=True)),
                ('effort', models.DurationField(blank=True, help_text='Estimated number of hours:minutes [hh:mm] needed to complete this chapter.', null=True)),
                ('slug', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('hidden', models.BooleanField(default=False)),
                ('course_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='course_metadata.CourseRun')),
            ],
            options={
                'get_latest_by': 'modified',
                'ordering': ('-modified', '-created'),
                'abstract': False,
            },
        ),
    ]
