# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-10-18 19:30
from __future__ import unicode_literals

from django.db import migrations
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0058_chapter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='course_run',
        ),
        migrations.AddField(
            model_name='courserun',
            name='chapters',
            field=sortedm2m.fields.SortedManyToManyField(help_text=None, related_name='course_runs', to='course_metadata.Chapter'),
        ),
    ]
