# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-10-19 00:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0059_auto_20181018_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='goal_override',
            field=models.TextField(blank=True, default=None, help_text='Goal description specific for this chapter within the course.', null=True),
        ),
        migrations.AddField(
            model_name='chapter',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
