# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-10-19 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0061_chapter_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapter',
            old_name='effort',
            new_name='min_effort',
        ),
        migrations.AddField(
            model_name='chapter',
            name='max_effort',
            field=models.DurationField(blank=True, help_text='Average number of hours:minutes [hh:mm] needed to complete this chapter.', null=True),
        ),
    ]
