# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-10-19 02:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0062_auto_20181019_0209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapter',
            old_name='key',
            new_name='location',
        ),
    ]
