# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-10-21 03:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0065_auto_20181019_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequential',
            name='chapter_order',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Order presented in the Chapter within the course.', null=True),
        ),
    ]
