# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-10-21 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0066_sequential_chapter_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='course_order',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Order presented within the course.', null=True),
        ),
    ]
