# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-10-21 14:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0067_chapter_course_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequential',
            name='course_run',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sequentials', to='course_metadata.CourseRun'),
            preserve_default=False,
        ),
    ]
