# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-10-25 04:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0074_courserun_invitation_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='slug',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
