# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-10 16:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0078_auto_20181110_1547'),
    ]

    operations = [
        migrations.RenameField(
            model_name='simulation',
            old_name='course_runs',
            new_name='sequentials',
        ),
    ]
