# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-10 18:06
from __future__ import unicode_literals

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0079_auto_20181110_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulation',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title'),
        ),
    ]
