# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-10 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0081_auto_20181110_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simulationmode',
            name='description_override',
        ),
        migrations.AddField(
            model_name='simulationmode',
            name='full_description_override',
            field=models.TextField(blank=True, default=None, help_text='Full description specific for this simulation type.', null=True),
        ),
    ]
