# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-10 20:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_partner_lms_url'),
        ('course_metadata', '0082_auto_20181110_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Partner'),
        ),
    ]
