# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-12 03:53
from __future__ import unicode_literals

from django.db import migrations
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0083_simulation_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequential',
            name='simulations',
            field=sortedm2m.fields.SortedManyToManyField(help_text=None, related_name='sequential_simulations', to='course_metadata.Simulation'),
        ),
        migrations.AlterField(
            model_name='sequential',
            name='objectives',
            field=sortedm2m.fields.SortedManyToManyField(help_text=None, related_name='sequential_objectives', to='course_metadata.Objective'),
        ),
    ]
