# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-07-25 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0084_auto_20180522_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='courserun',
            name='wordpress_post_id',
            field=models.BigIntegerField(blank=True, editable=False, help_text='This is the Wordpress Post id generated from the marketing frontend.', null=True),
        ),
    ]
