# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-07-25 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0087_auto_20190725_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='course_order',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Order presented within the course.', null=True),
        ),
        migrations.AddField(
            model_name='sequential',
            name='chapter_order',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Order presented in the Chapter within the course.', null=True),
        ),
    ]
