# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-07-25 16:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0089_auto_20190725_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='course_run',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='chapters_accessor', to='course_metadata.CourseRun'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chapter',
            name='wordpress_post_id',
            field=models.BigIntegerField(blank=True, editable=False, help_text='This is the Wordpress Post id generated from the marketing frontend.', null=True),
        ),
        migrations.AlterField(
            model_name='sequential',
            name='course_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequentials_accessor', to='course_metadata.CourseRun'),
        ),
    ]
