# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-07-25 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0090_auto_20190725_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courserun',
            name='max_effort',
            field=models.DurationField(blank=True, help_text='Average number of hours:minutes:seconds [hh:mm:ss] needed to complete this chapter.', null=True),
        ),
        migrations.AlterField(
            model_name='courserun',
            name='min_effort',
            field=models.DurationField(blank=True, help_text='Estimated number of hours:minutes:seconds [hh:mm:ss] needed to complete this chapter.', null=True),
        ),
    ]
