# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-07-25 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0092_auto_20190725_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='courserun',
            name='invitation_only',
            field=models.BooleanField(default=False),
        ),
    ]
