# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-07-25 17:55
from __future__ import unicode_literals

from django.db import migrations, models
import djchoices.choices


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0094_auto_20190725_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='status',
            field=models.CharField(choices=[('published', 'Published'), ('unpublished', 'Unpublished')], db_index=True, default='published', max_length=255, validators=[djchoices.choices.ChoicesValidator({'published': 'Published', 'unpublished': 'Unpublished'})]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sequential',
            name='status',
            field=models.CharField(choices=[('published', 'Published'), ('unpublished', 'Unpublished')], db_index=True, default='published', max_length=255, validators=[djchoices.choices.ChoicesValidator({'published': 'Published', 'unpublished': 'Unpublished'})]),
            preserve_default=False,
        ),
    ]
