# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-07-25 18:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190725_1352'),
        ('course_metadata', '0096_auto_20190725_1812'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationMode',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('full_description_override', models.TextField(blank=True, default=None, help_text='Full description specific for this simulation type.', null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='simulation',
            name='simulation_mode',
        ),
        migrations.AddField(
            model_name='simulation',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Partner'),
        ),
        migrations.AddField(
            model_name='simulation',
            name='simulation_modes',
            field=models.ManyToManyField(blank=True, related_name='simulation_modes', to='course_metadata.SimulationMode'),
        ),
    ]
