# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-07-27 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0098_auto_20190725_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='lms_web_url',
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='sequential',
            name='lms_web_url',
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
    ]
